### ISSUE TITLE
why this is valid {{{}}} bro in console?

### ISSUE THREAD

**Issue by Aju100** [anuraghazra/anuraghazra#2]

**Comment by anuraghazra** [comment]
@Aju100 well those are just plain simple block scopes also called "block statements" 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block


Block scopes can be used to isolate same named variables and reusing the name instead of doing "var1", "var2" although i never used it, did not find any good usecases for them
```js
{
   const blocked_scoped = 1;
   console.log(blocked_scoped)
}
{
   const blocked_scoped = 2;
   console.log(blocked_scoped)
}
```

So `{{{}}}` is just nested block scopes.

**Comment by anuraghazra** [comment]
Thanks for asking the question @Aju100 I hope you got your answers. Closing this now :ok_hand:
